### ISSUE TITLE
Implement short-circuit evaluation

### ISSUE THREAD

**Issue by Shahar-Ben-Ezra** [regevbr/json-expression-eval#4]
in the `handleOrOp` and `handleAndOp` functions `forEach` calls a provided callback function once for each element but it's not necessary to call all the elements if we already got true in one of the elements evaluate.

**suggested solution -** 
At `handleOrOp` and `handleAndOp` functions need to return result earlier at `forEach` method if the result variable is true at `handleOrOp` or false at` handleAndOp`.

_I would like to create PR to fix it._

**Comment by regevbr** [comment]
@Shahar-Ben-Ezra go for it, don't forget to add tests
